version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_test
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    networks:
      - sensor-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    volumes:
      - ./ops/new_database.sql:/docker-entrypoint-initdb.d/new_database.sql

networks:
  sensor-network:
    driver: bridge
